#!/bin/bash
# compile debug

if test -f sfmlapp
then
    rm sfmlapp;
fi

g++ -std=c++17 -Wall -Werror -pedantic -Wextra -O2 -ffast-math -c main.cpp
g++ main.o -o sfmlapp -lsfml-graphics -lsfml-window -lsfml-system

if test -f main.o
then
    rm main.o
fi
if test -f sfmlapp
then 
    chmod 777 sfmlapp
    ./sfmlapp
fi